import { makeAjvWithTextKeywords } from '../core/ajv-setup';
import type { ValidationResult } from '../types';
import schema from '../../schemas/prompt-bundle.meta.schema.json';

/**
 * Validate a Prompt Bundle
 *
 * A Prompt Bundle contains everything needed for an OpenAI API call:
 * - System and user messages
 * - Field guide (AI field metadata)
 * - Context (sliced NAS data)
 * - Response format (AIS schema)
 *
 * Generated by the composition domain from templates and data.
 *
 * @param doc - Unknown input to validate
 * @returns ValidationResult with ok status and any errors
 */
export function validatePromptBundle(doc: unknown): ValidationResult {
  const ajv = makeAjvWithTextKeywords();
  const validate = ajv.compile(schema);
  const ok = validate(doc);

  return {
    ok,
    errors: validate.errors ?? [],
    warnings: []
  };
}
